name: Build Plugin

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: gradlew calistirilabilir yap
        run: chmod +x gradlew

      - name: Build Plugins
        run: ./gradlew make --stacktrace

      - name: .cs3 dosyalarini yukle
        uses: actions/upload-artifact@v4
        with:
          name: cs3-eklentiler
          path: "**/build/*.cs3"
          if-no-files-found: error
